{"name": "Acessar detalhe de um Fundo de Investimento", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <tr class=\"MuiTableRow-root\" index=\"0\" level=\"0\" path=\"0\" scrollwidth=\"783\" style=\"transition: all 300ms ease 0s; background-color: rgb(244, 242, 237);\">...</tr> is not clickable at point (391, 393). Other element would receive the click: <p>...</p>\n  (Session info: headless chrome=90.0.4430.212)\n\n", "trace": "  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\navegacao_step.py\", line 33, in step_impl\n    context.vortx.clicar_detalhe_fundo_investimento(context)\n  File \"C:\\Users\\luis.gimenez\\Documents\\TesteVortx\\features\\pages\\NavegacaoPage.py\", line 41, in clicar_detalhe_fundo_investimento\n    (By.XPATH, \"//*[@id='__next']/div/section[1]/div[2]/div/div[2]/div/div/div/table/tbody/tr[1]\"))).click()\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Dado que esteja home page da Vortx", "status": "passed", "start": 1621228531807, "stop": 1621228532554}, {"name": "Dado que eu esteja na pagina de Fundos de investimento", "status": "passed", "start": 1621228532554, "stop": 1621228532749}, {"name": "Quando eu clicar no detalhe de um fundo", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <tr class=\"MuiTableRow-root\" index=\"0\" level=\"0\" path=\"0\" scrollwidth=\"783\" style=\"transition: all 300ms ease 0s; background-color: rgb(244, 242, 237);\">...</tr> is not clickable at point (391, 393). Other element would receive the click: <p>...</p>\n  (Session info: headless chrome=90.0.4430.212)\n\n", "trace": "  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\navegacao_step.py\", line 33, in step_impl\n    context.vortx.clicar_detalhe_fundo_investimento(context)\n  File \"C:\\Users\\luis.gimenez\\Documents\\TesteVortx\\features\\pages\\NavegacaoPage.py\", line 41, in clicar_detalhe_fundo_investimento\n    (By.XPATH, \"//*[@id='__next']/div/section[1]/div[2]/div/div[2]/div/div/div/table/tbody/tr[1]\"))).click()\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\luis.gimenez\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1621228532749, "stop": 1621228534902}, {"name": "Então o sistema deve exibir  carregando do fundo selecionado", "status": "skipped", "start": 1621228534902, "stop": 1621228534902}], "start": 1621228531807, "stop": 1621228534902, "uuid": "c1444847-2ada-4a72-af66-daa4be07614a", "historyId": "d310cb1d7d776a5cedbcfd1a80dffa64", "fullName": "Desafio - Laboratório Automação: Acessar detalhe de um Fundo de Investimento", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "cenario2"}, {"name": "feature", "value": "Desafio - Laboratório Automação"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}